In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("background_place_holder.jpg")
print(img)
print(img.shape)
img = cv2.resize(img, (500, 500))
cv2.imshow("pic", img)
cv2.waitKey(100)

[[[139 172 198]
  [140 173 199]
  [140 173 199]
  ...
  [190 196 203]
  [188 194 201]
  [187 193 200]]

 [[141 174 200]
  [141 174 200]
  [141 174 200]
  ...
  [191 197 204]
  [189 195 202]
  [187 193 200]]

 [[143 176 202]
  [142 175 201]
  [142 175 201]
  ...
  [191 197 204]
  [189 195 202]
  [188 194 201]]

 ...

 [[ 22  34  40]
  [ 23  35  41]
  [ 25  37  43]
  ...
  [ 63  62  64]
  [ 62  61  63]
  [ 62  61  63]]

 [[ 23  35  41]
  [ 20  32  38]
  [ 21  33  39]
  ...
  [ 63  62  64]
  [ 62  61  63]
  [ 64  63  65]]

 [[ 26  38  44]
  [ 20  32  38]
  [ 19  31  37]
  ...
  [ 62  61  63]
  [ 62  61  63]
  [ 66  65  67]]]
(960, 1440, 3)


-1